### ISSUE TITLE
Text potvrzovacího emailu

### ISSUE THREAD

**Issue by ondre28** [cesko-digital/pomahejukrajine-worker#14]
Prosím upravit text potvrzovacího emailu:
- místo nadpisu logo Pomáhej Ukrajině (v Čj a UA verzi): **EDIT - logo ne**, ponechat stávající nadpis
- celé textové pole v mailu roztáhnout, ať je širší
- velikost písma linku, aby bylo stejně velké jako text kolem. Bold ponechat, barvu změnit na modrou, která se používá na webu Pomáhej Ukrajině 
- barva textu (kromě barvy linku) aby byla černá. 

![Image](https://user-images.githubusercontent.com/116279861/217236634-02e237d9-9749-4799-b013-432f74530dba.png)

**Comment by hankadev** [comment]
@ondre28 mam na to pripravene PR: https://github.com/cesko-digital/pomahejukrajine-worker/pull/15.. nasazuje se to zvlast nez web.. akorat taky tam je nejaky problem s Vercelem.. tak az to Honza nebo nekdo kdo ma pristup opravi, tak je mozne to PR mergnout, otestovat a pripadne nasadit.

**Comment by ondre28** [comment]
@hanny21 Ahoj, děkuju! Problém s vercelem řešíme už několik dní, nějak ale nevíme, kde je ta příčina.
